dist: trusty
language: python
python:
 - "2.7"
 - "3.5"
install:
 - pip install --upgrade pip
 - pip --version
 - pip install tensorflow==1.5.0
 - pip install tensor2tensor==1.5.7
 - python setup.py build
script:
 - python setup.py test

